# Generated by scripts/build_skill.py; edit src/compass_c instead.
"""Explicit, local evidence replacement batches with inspectable consequences.

Callers supply the observations and opaque source references. Preview never writes;
apply rechecks the revision and commits all replacements together. Neither function
fetches evidence, monitors a decision, interprets prose conditions, or permits action.
"""

from __future__ import annotations

import json
import sqlite3
import uuid
from typing import Any

from core import CompassError, Notebook, identifier, integer, strings, text, utc

UPDATE_KINDS = frozenset({"evidence", "assumption", "forecast", "outcome"})
UPDATE_FIELDS = frozenset({"note_id", "content", "reason", "status", "source"})


def _parse(updates: Any) -> list[dict[str, Any]]:
    if type(updates) is not list or not 1 <= len(updates) <= 64:
        raise CompassError("INVALID_INPUT", "updates must contain between 1 and 64 replacements")
    parsed = []
    roots: set[str] = set()
    for update in updates:
        if (
            type(update) is not dict
            or not UPDATE_FIELDS <= update.keys()
            or update.keys() - UPDATE_FIELDS - {"depends_on"}
        ):
            raise CompassError(
                "INVALID_INPUT",
                "Each update requires note_id, content, reason, status, source; "
                "only depends_on is optional",
            )
        entry = {
            "supersedes": identifier(update["note_id"], "note_id"),
            "content": text(update["content"], "content"),
            "reason": text(update["reason"], "reason"),
            "status": text(update["status"], "status", limit=30),
            "source": text(update["source"], "source", limit=4_000, empty=True),
        }
        if entry["status"] not in {"observed", "computed"}:
            raise CompassError(
                "INVALID_INPUT", "Evidence updates require observed or computed status"
            )
        if not entry["source"].strip():
            raise CompassError("SOURCE_REQUIRED", "Observed/computed notes need provenance")
        if entry["supersedes"] in roots:
            raise CompassError("INVALID_INPUT", "A batch cannot replace the same note twice")
        roots.add(entry["supersedes"])
        if "depends_on" in update:
            dependencies = strings(update["depends_on"], "depends_on")
            for dependency in dependencies:
                identifier(dependency, "dependency")
            if len(dependencies) != len(set(dependencies)):
                raise CompassError("INVALID_INPUT", "Duplicate dependencies")
            entry["depends_on"] = dependencies
        parsed.append(entry)
    return parsed


def _prepare(
    notebook: Notebook,
    database: sqlite3.Connection,
    decision_id: str,
    expected_revision: int,
    updates: list[dict[str, Any]],
) -> tuple[dict[str, Any], list[set[str]]]:
    snapshot = notebook._snapshot(database, decision_id)
    notebook._revision(snapshot, expected_revision)
    if notebook._verify_schema(database) not in {"2", "3"}:
        raise CompassError("MIGRATION_REQUIRED", "Run migrate explicitly before evidence updates")
    notes = {note["id"]: note for note in snapshot["notes"]}
    if len(notes) + len(updates) > 2_000:
        raise CompassError("CAPACITY", "The complete batch would exceed the decision note limit")
    replaced = {entry["supersedes"] for entry in snapshot["revisions"]}
    impacts = []
    roots = {entry["supersedes"] for entry in updates}
    for entry in updates:
        root = entry["supersedes"]
        if root not in notes:
            raise CompassError("NOT_FOUND", "Note not found in this decision")
        if root in replaced:
            raise CompassError("NOTE_SUPERSEDED", "Revise the replacement note instead")
        if notes[root]["kind"] not in UPDATE_KINDS:
            raise CompassError(
                "INVALID_INPUT",
                "Evidence batches replace evidence, assumption, forecast, or outcome notes; "
                "reconsider other note kinds explicitly with revise",
            )
        affected = notebook._affected(snapshot["notes"], root)
        if (roots - {root}) & affected:
            raise CompassError(
                "INVALID_INPUT", "Batch roots must be independent; update dependent notes afterward"
            )
        impacts.append(affected)
        entry["kind"] = notes[root]["kind"]
        entry.setdefault("depends_on", list(notes[root]["depends_on"]))
    all_affected = set().union(*impacts)
    for entry in updates:
        for dependency in entry["depends_on"]:
            if dependency not in notes:
                raise CompassError("INVALID_DEPENDENCY", "Dependency belongs elsewhere")
            if notes[dependency]["stale"] or dependency in all_affected:
                raise CompassError("STALE_DEPENDENCY", "Cannot build on invalidated evidence")
    return snapshot, impacts


def _result(
    snapshot: dict[str, Any],
    updates: list[dict[str, Any]],
    impacts: list[set[str]],
    *,
    applied: bool,
) -> dict[str, Any]:
    return {
        "decision_id": snapshot["decision_id"],
        "revision": snapshot["revision"],
        "applied": applied,
        "updates": updates,
        "invalidated": sorted(set().union(*impacts)),
        "review": {
            "status": "human_review_required",
            "conditions_evaluated": False,
            "reversal_conditions": [
                note for note in snapshot["notes"] if note["kind"] == "reversal_condition"
            ],
            "outcomes": [note for note in snapshot["notes"] if note["kind"] == "outcome"],
            "next_checks": [
                "Compare the supplied observations with the recorded reversal conditions; "
                "COMPASS-C has not interpreted whether any condition occurred.",
                "Reconsider affected reasoning and recommendations using current evidence.",
                "Record observed outcomes with provenance and distinguish them from forecasts.",
            ],
        },
        "scope": "analysis_only",
        "action_permission": "not_granted",
        "source_verified": False,
    }


def preview_updates(
    notebook: Notebook,
    decision_id: str,
    expected_revision: int,
    updates: list[dict[str, Any]],
) -> dict[str, Any]:
    """Validate a supplied batch and show its impact without changing storage.

    Preview is neither a reservation nor an approval token. A subsequent apply
    must supply the same expected revision and is validated again independently.
    """
    identifier(decision_id, "decision_id")
    integer(expected_revision, "expected_revision", 1)
    parsed = _parse(updates)
    with notebook._existing_connection(writable=False) as database:
        snapshot, impacts = _prepare(notebook, database, decision_id, expected_revision, parsed)
        return _result(snapshot, parsed, impacts, applied=False)


def apply_updates(
    notebook: Notebook,
    decision_id: str,
    expected_revision: int,
    updates: list[dict[str, Any]],
) -> dict[str, Any]:
    """Opt in to an all-or-nothing replacement batch at one expected revision.

    Original notes and sources remain in history. Dependencies and all previous
    recommendations become stale as in ``Notebook.revise``. Roots must be
    independent: there is no implicit rebinding to other replacements in the batch.
    """
    identifier(decision_id, "decision_id")
    integer(expected_revision, "expected_revision", 1)
    parsed = _parse(updates)
    with notebook._existing_connection(writable=True) as database:
        _, impacts = _prepare(notebook, database, decision_id, expected_revision, parsed)
        revision = expected_revision + 1
        for entry, affected in zip(parsed, impacts, strict=True):
            notebook._write_invalidation(
                database, decision_id, revision, entry["supersedes"], entry["reason"], affected
            )
            replacement_id = uuid.uuid4().hex
            timestamp = utc()
            database.execute(
                "INSERT INTO notes VALUES (?, ?, ?, ?, ?, ?, ?, 0, ?)",
                (
                    replacement_id,
                    decision_id,
                    entry["kind"],
                    entry["content"],
                    entry["status"],
                    entry["source"],
                    json.dumps(entry["depends_on"]),
                    timestamp,
                ),
            )
            database.execute(
                "INSERT INTO note_revisions VALUES (?, ?, ?, ?, ?, ?, ?)",
                (
                    uuid.uuid4().hex,
                    decision_id,
                    entry["supersedes"],
                    replacement_id,
                    entry["reason"],
                    revision,
                    timestamp,
                ),
            )
            entry["note_id"] = replacement_id
        return _result(notebook._snapshot(database, decision_id), parsed, impacts, applied=True)
