#!/usr/bin/env python3
"""Generate the portable COMPASS skill scripts from the canonical package."""

from __future__ import annotations

import argparse
import difflib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "compass_c"
TARGET = ROOT / "skills" / "compass" / "scripts"
GENERATED = "# Generated by scripts/build_skill.py; edit src/compass_c instead.\n"


def outputs() -> dict[Path, str]:
    core = GENERATED + (SOURCE / "core.py").read_text(encoding="utf-8")
    calculations = (
        (SOURCE / "calculations.py")
        .read_text(encoding="utf-8")
        .replace("from .core import", "from core import")
    )
    cli = (
        (SOURCE / "cli.py")
        .read_text(encoding="utf-8")
        .replace(
            "from . import VERSION, CompassError, Notebook, calculate",
            (
                "sys.path.insert(0, str(Path(__file__).resolve().parent))\n"
                "from calculations import calculate  # noqa: E402\n"
                "from core import VERSION, CompassError, Notebook  # noqa: E402"
            ),
        )
    )
    return {
        TARGET / "core.py": core,
        TARGET / "calculations.py": GENERATED + calculations,
        TARGET / "compass.py": GENERATED + cli,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated files drift")
    args = parser.parse_args()
    drifted = False
    for path, expected in outputs().items():
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual == expected:
            continue
        drifted = True
        if args.check:
            print(
                "".join(
                    difflib.unified_diff(
                        actual.splitlines(keepends=True),
                        expected.splitlines(keepends=True),
                        fromfile=str(path),
                        tofile=f"generated:{path}",
                    )
                ),
                end="",
            )
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
    return 1 if args.check and drifted else 0


if __name__ == "__main__":
    raise SystemExit(main())
