#!/usr/bin/env python3
"""Generate the portable COMPASS skill scripts from the canonical package."""

from __future__ import annotations

import argparse
import difflib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "compass_c"
TARGET = ROOT / "skills" / "compass" / "scripts"
GENERATED = "# Generated by scripts/build_skill.py; edit src/compass_c instead.\n"
PORTABLE_MODULES = ("core", "calculations", "evaluation", "evidence", "portfolio", "experiments")


def portable_imports(source: str) -> str:
    for module in PORTABLE_MODULES:
        source = source.replace(f"from .{module} import", f"from {module} import")
    return source


def outputs() -> dict[Path, str]:
    cli = (
        (SOURCE / "cli.py")
        .read_text(encoding="utf-8")
        .replace(
            "from . import VERSION, CompassError, Notebook, calculate",
            (
                "sys.path.insert(0, str(Path(__file__).resolve().parent))\n"
                "from calculations import calculate  # noqa: E402\n"
                "from core import VERSION, CompassError, Notebook  # noqa: E402"
            ),
        )
        .replace(
            "from .evaluation import evaluate", "from evaluation import evaluate  # noqa: E402"
        )
        .replace(
            "from .evidence import apply_updates, preview_updates",
            "from evidence import apply_updates, preview_updates  # noqa: E402",
        )
        .replace(
            "from .core import KINDS, STATUSES", "from core import KINDS, STATUSES  # noqa: E402"
        )
    )
    result = {
        TARGET / f"{module}.py": GENERATED
        + portable_imports((SOURCE / f"{module}.py").read_text(encoding="utf-8"))
        for module in PORTABLE_MODULES
    }
    result[TARGET / "compass.py"] = GENERATED + cli
    return result


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated files drift")
    args = parser.parse_args()
    drifted = False
    for path, expected in outputs().items():
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual == expected:
            continue
        drifted = True
        if args.check:
            print(
                "".join(
                    difflib.unified_diff(
                        actual.splitlines(keepends=True),
                        expected.splitlines(keepends=True),
                        fromfile=str(path),
                        tofile=f"generated:{path}",
                    )
                ),
                end="",
            )
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
    return 1 if args.check and drifted else 0


if __name__ == "__main__":
    raise SystemExit(main())
